
-- Tabela de Vagas de Emprego
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    description TEXT NOT NULL,
    salary TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('CLT', 'Estágio', 'PJ', 'Temporário')),
    location TEXT NOT NULL,
    date TEXT, -- Armazena data original textual ou ISO
    contact_link TEXT NOT NULL,
    logo_url TEXT,
    requirements TEXT[], -- Array de strings
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Segurança)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Política: Todos podem ver (Público)
CREATE POLICY "Public jobs are viewable by everyone" 
ON jobs FOR SELECT 
USING (true);

-- Política: Apenas service_role ou autenticado pode inserir (Mas vamos deixar aberto para Anon por enquanto se for via API sem Auth, ou melhor, restringir. Como o Admin usa apenas senha local, a inserção será feita pelo Client anonimo. Então precisamos liberar insert para anonimo POR ENQUANTO, mas o ideal é proteger).
-- Dado que o AdminPage usa senha local, o client é anonimo.
CREATE POLICY "Enable insert for anon (temporary)" 
ON jobs FOR INSERT 
WITH CHECK (true);

-- Política: Update/Delete também para anon por enquanto (facilitator)
CREATE POLICY "Enable update for anon" 
ON jobs FOR UPDATE 
USING (true);

CREATE POLICY "Enable delete for anon" 
ON jobs FOR DELETE 
USING (true);
