-- Tabela de Notícias (News)
create table public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text,
  image_url text,
  category text,
  category_color text,
  publish_date timestamp with time zone default timezone('utc'::text, now()),
  author text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Eventos (Events)
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  date timestamp with time zone,
  time text,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela de Comércio (Businesses)
create table public.businesses (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  image_url text,
  address text,
  phone text,
  website text,
  description text,
  is_featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar Row Level Security (RLS) - Segurança
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.businesses enable row level security;

-- Criar políticas de acesso (Todo mundo pode ler, só autenticado pode escrever)
-- News
create policy "Public News Access" on public.news
for select using (true);

create policy "Admin News Insert" on public.news
for insert with check (true); -- Temporariamente aberto para facilitar, ideal restringir depois

create policy "Admin News Update" on public.news
for update using (true);

create policy "Admin News Delete" on public.news
for delete using (true);

-- Events
create policy "Public Events Access" on public.events
for select using (true);

create policy "Admin Events Insert" on public.events
for insert with check (true);

create policy "Admin Events Update" on public.events
for update using (true);

create policy "Admin Events Delete" on public.events
for delete using (true);

-- Businesses
create policy "Public Business Access" on public.businesses
for select using (true);

create policy "Admin Business Insert" on public.businesses
for insert with check (true);

create policy "Admin Business Update" on public.businesses
for update using (true);

create policy "Admin Business Delete" on public.businesses
for delete using (true);

-- Inserir Dados Iniciais (Notícias)
insert into public.news (id, title, summary, content, image_url, category, category_color, publish_date, author)
values
(101, 'Araucária zera fila de espera por vagas em CMEIs para 2025', 'Prefeitura anuncia que todas as 1.500 crianças de 0 a 3 anos inscritas tiveram vagas ofertadas.', '<p>Um marco histórico para a educação de Araucária. A Secretaria Municipal de Educação confirmou nesta semana que a fila de espera por vagas em Centros Municipais de Educação Infantil (CMEIs) foi totalmente zerada.</p><p>O avanço beneficia cerca de 1.500 famílias que aguardavam vaga para o ano letivo de 2025. "Trabalhamos duro na ampliação das unidades e em parcerias para garantir esse direito fundamental", afirmou a secretária de educação.</p>', '/images/news_cmei_2025.png', 'Educação', 'red', NOW(), 'Redação Municipal'),
(102, 'Orçamento Municipal para 2026 deve chegar a R$ 2,3 bilhões', 'Previsão orçamentária aponta crescimento na arrecadação e maiores investimentos em obras e saúde.', '<p>A Lei Orçamentária Anual (LOA) discutida na Câmara Municipal projeta um orçamento recorde de aproximadamente R$ 2,3 bilhões para Araucária em 2026.</p><p>A prioridade dos recursos será para a manutenção dos serviços de saúde e grandes obras de infraestrutura viária, como a duplicação de avenidas importantes e a construção do novo hospital.</p>', '/images/news_budget.png', 'Economia', 'blue', NOW() - interval '1 day', 'Câmara Municipal'),
(103, 'Governador inaugura unidade do Poupatempo em Araucária', 'Nova agência no centro unifica mais de 240 serviços estaduais e facilita a vida do cidadão.', '<p>Foi inaugurada oficialmente a primeira unidade de rua do Poupatempo no Paraná, localizada em Araucária. O espaço moderno facilita a vida do cidadão, permitindo emitir documentos como RG e CNH, além de solicitar serviços da Copel e Sanepar em um único lugar.</p><p>"É o fim da burocracia e das filas. O cidadão resolve tudo em um só lugar", destacou o governador Ratinho Jr durante a cerimônia.</p>', '/images/custom_poupatempo_official.jpg', 'Cidade', 'blue', NOW() - interval '2 days', 'Agência Estadual'),
(104, 'Pacote de investimentos federais destina R$ 20 milhões para Araucária', 'Recursos anunciados pelo Governo Federal serão aplicados na saúde e educação.', '<p>Em visita oficial, representantes do Governo Federal anunciaram um pacote de investimentos para Araucária. Serão R$ 2,8 milhões destinados à Saúde e R$ 18 milhões para a Educação, focados na ampliação da rede física de atendimento.</p>', '/images/news_investments.png', 'Política', 'purple', NOW() - interval '3 days', 'Brasília News'),
(105, 'Polícia Civil incinera 114 kg de drogas apreendidas na região', 'Ação realizada nesta semana marca o combate efetivo ao tráfico em Araucária.', '<p>A Polícia Civil do Paraná (PCPR) realizou a incineração de mais de 114 quilos de entorpecentes apreendidos em operações recentes em Araucária.</p>', '/images/custom_drugs.jpg', 'Segurança', 'red', NOW() - interval '3 days', 'PCPR'),
(106, 'Vacinação contra Vírus Sincicial Respiratório (VSR) para gestantes', 'Saúde inicia imunização para proteger recém-nascidos de infecções graves.', '<p>A Secretaria Municipal de Saúde iniciou a campanha de vacinação contra o VSR voltada para gestantes. A medida visa transmitir anticorpos para o bebê ainda na gestação.</p>', '/images/vacinacao_meta_2024.jpg', 'Saúde', 'blue', NOW() - interval '4 days', 'Saúde Agora'),
(107, 'Cantata de Natal emociona fiéis no Santuário', 'Apresentação "Um Conto de Natal" reuniu centenas de pessoas no fim de semana.', '<p>O clima natalino tomou conta de Araucária com a belíssima apresentação da Cantata "Um Conto de Natal" na Paróquia Nossa Senhora do Perpétuo Socorro.</p>', '/images/cantata_natal_real.png', 'Cultura', 'indigo', NOW() - interval '5 days', 'Cultura Viva'),
(108, 'Ciclone extratropical: Equipes trabalham para restabelecer energia', 'Após tempestade, Copel atua para religar 21 unidades consumidoras ainda sem luz.', '<p>O ciclone extratropical que atingiu a região sul nos últimos dias deixou estragos pontuais em Araucária.</p>', '/images/news_cyclone_energy.png', 'Cidade', 'gray', NOW() - interval '6 days', 'Tempo Agora'),
(109, 'Ginásio Joval de Paula Souza será reformado', 'Prefeitura anuncia revitalização completa do complexo esportivo no Parque Cachoeira.', '<p>Um dos principais palcos do esporte araucariense, o Ginásio Joval de Paula Souza, passará por uma ampla reforma.</p>', '/images/custom_gym_official.png', 'Esporte', 'green', NOW() - interval '4 days', 'Esporte News'),
(6, 'Câmara aprova incentivo ao turismo rural', 'Caminho do Guajuvira e roteiros poloneses receberão verba para sinalização e melhorias.', '<p>Em sessão realizada ontem, a Câmara Municipal de Araucária aprovou por unanimidade o projeto de lei que cria incentivos fiscais e destina verbas para o desenvolvimento do turismo rural na região.</p>', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1000', 'Turismo', 'indigo', NOW() - interval '9 days', 'Jornal do Campo'),
(7, 'Campanha de Vacinação atinge meta no município', 'Secretaria de Saúde comemora alta adesão da população na campanha contra a gripe.', '<p>A Secretaria Municipal de Saúde de Araucária divulgou hoje que a campanha de vacinação contra a gripe atingiu 95% da meta estipulada para o público-alvo.</p>', '/images/vacinacao_meta_2024.jpg', 'Cidade', 'blue', NOW() - interval '10 days', 'Saúde em Foco'),
(8, 'Festival de Teatro Infantil lota auditórios', 'Semana da criança foi marcada por apresentações culturais gratuitas em diversas escolas.', '<p>A magia do teatro invadiu as escolas municipais de Araucária. O Festival de Teatro Infantil, promovido pela Secretaria de Cultura, realizou mais de 20 apresentações gratuitas ao longo da última semana.</p>', '/images/placeholder_educacao.png', 'Educação', 'red', NOW() - interval '12 days', 'Cultura Viva'),
(9, 'Novas ciclovias conectam bairros industriais', 'Projeto de mobilidade urbana facilita o deslocamento de trabalhadores para a área industrial.', '<p>A Prefeitura iniciou as obras de expansão da malha cicloviária na região industrial. O projeto prevê a conexão entre os bairros residenciais e o complexo da REPAR.</p>', '/images/ciclovia_industrial.jpg', 'Infraestrutura', 'purple', NOW() - interval '14 days', 'Mobilidade Urbana'),
(10, 'Operação Tapa-Buracos avança no Jardim Iguaçu', 'Equipes da Secretaria de Obras trabalham em ritmo acelerado para recuperar vias danificadas pelas chuvas.', '<p>A Secretaria de Obras Públicas intensificou nesta semana a Operação Tapa-Buracos no bairro Jardim Iguaçu.</p>', '/images/tapa_buracos_real_final.jpg', 'Infraestrutura', 'purple', NOW() - interval '15 days', 'Redação Municipal'),
(11, 'Guarda Municipal recebe novas viaturas', 'Investimento na segurança pública inclui renovação da frota e novos equipamentos de proteção.', '<p>A Guarda Municipal de Araucária recebeu hoje 5 novas viaturas totalmente equipadas para o patrulhamento preventivo.</p>', '/images/custom_gm_official_jeep.jpg', 'Cidade', 'blue', NOW() - interval '16 days', 'Segurança em Pauta'),
(12, 'Hospital Municipal inaugura nova ala pediátrica', 'Ampliação promete dobrar a capacidade de atendimento infantil e conta com equipamentos de última geração.', '<p>O Hospital Municipal de Araucária (HMA) inaugurou nesta manhã sua nova ala pediátrica.</p>', '/images/custom_hospital_official.jpg', 'Cidade', 'blue', NOW() - interval '18 days', 'Saúde Agora'),
(13, 'Feira de Robótica reúne estudantes da rede pública', 'Alunos apresentaram projetos inovadores focados em sustentabilidade e automação.', '<p>O Parque Cachoeira foi palco da 5ª Feira de Robótica e Inovação das escolas municipais.</p>', 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&q=80&w=1000', 'Educação', 'red', NOW() - interval '20 days', 'EducaTech'),
(14, 'Novo supermercado gera 200 empregos diretos', 'Grande rede varejista abre as portas no bairro Costeira, movimentando a economia local.', '<p>A economia de Araucária ganhou um reforço importante nesta semana com a inauguração de uma nova unidade de uma grande rede de supermercados no bairro Costeira.</p>', 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&q=80&w=1000', 'Cidade', 'blue', NOW() - interval '21 days', 'Economia Local'),
(15, 'Limpeza do Rio Iguaçu retira 5 toneladas de lixo', 'Ação voluntária mobilizou comunidade e ONGs ambientais no último fim de semana.', '<p>Um mutirão de limpeza realizado nas margens do Rio Iguaçu, no trecho que corta Araucária, resultou na retirada de mais de 5 toneladas de resíduos sólidos.</p>', '/images/limpeza_rio_iguacu_real.jpg', 'Cidade', 'blue', NOW() - interval '22 days', 'EcoAção'),
(16, 'Torneio de Xadrez movimenta o fim de semana', 'Competição reuniu enxadristas de todas as idades no Centro de Convivência.', '<p>O raciocínio lógico e a estratégia foram os protagonistas no Torneio Municipal de Xadrez, realizado neste sábado.</p>', 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&q=80&w=1000', 'Esporte', 'green', NOW() - interval '25 days', 'Esporte Araucária'),
(17, 'Curso gratuito de qualificação profissional abre inscrições', 'Senai e Prefeitura oferecem vagas para cursos na área industrial e administrativa.', '<p>Estão abertas as inscrições para os cursos gratuitos de qualificação profissional oferecidos em parceria entre a Prefeitura de Araucária e o Senai.</p>', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1000', 'Educação', 'red', NOW() - interval '28 days', 'Carreira e Futuro'),
(18, 'Rota de Turismo Rural ganha nova sinalização', 'Prefeitura instala placas indicativas no Caminho do Vinho e Guajuvira para orientar visitantes.', '<p>O Departamento de Turismo iniciou a instalação de novas placas de sinalização turística nas principais rotas rurais do município.</p>', '/images/rota_turismo_rural.jpg', 'Turismo', 'indigo', NOW() - interval '30 days', 'Turismo Araucária'),
(19, 'Startup local desenvolve app para transporte escolar', 'Aplicativo criado por jovens araucarienses permite aos pais rastrearem vans escolares em tempo real.', '<p>Uma startup incubada no parque tecnológico de Araucária lançou nesta semana um aplicativo inovador voltado para a segurança no transporte escolar.</p>', '/images/startup_app_real.jpg', 'Tecnologia', 'yellow', NOW() - interval '32 days', 'Inovação Tech'),
(20, 'Ginásio Joval de Paula Souza será reformado (Reprise)', 'Complexo esportivo receberá novo piso, iluminação de LED e melhorias na acessibilidade.', '<p>A Secretaria de Esporte e Lazer anunciou a reforma completa do Ginásio de Esportes Joval de Paula Souza, no Parque Cachoeira.</p>', 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=1000', 'Esporte', 'green', NOW() - interval '35 days', 'Esporte News'),
(21, 'Hackathon Municipal reúne 500 jovens programadores', 'Maratona de programação buscou soluções digitais para problemas urbanos da cidade.', '<p>O primeiro Hackathon Municipal de Araucária foi um sucesso absoluto.</p>', '/images/hackathon_real.jpg', 'Tecnologia', 'yellow', NOW() - interval '40 days', 'Tech News'),
(22, 'Sítio Ecológico abre novas trilhas para ecoturismo', 'Propriedade rural em Guajuvira aposta no turismo de natureza e observação de aves.', '<p>O turismo rural em Araucária ganhou mais uma atração de peso. O Sítio Ecológico Recanto das Águas inaugurou neste sábado três novas trilhas interpretativas em meio à mata nativa.</p>', '/images/sitio_ecologico_trilhas.jpg', 'Turismo', 'indigo', NOW() - interval '42 days', 'Jornal do Campo');

-- Sincronizar a sequência do ID para começar depois do último ID inserido
SELECT setval(pg_get_serial_sequence('public.news', 'id'), (SELECT MAX(id) FROM public.news));

-- Inserir Eventos
insert into public.events (id, title, description, image_url, date, time, location)
values
(1, 'Festa do Pêssego', 'A tradicional celebração da colheita com a melhor gastronomia polonesa e shows regionais.', '/images/festa_pessego_real.jpg', NOW() + interval '5 days', '18:00 - 23:00', 'Parque Cachoeira'),
(2, 'Feira Gastronômica Noturna', 'Pastel, pierogi e food trucks na praça central. Traga sua família!', '/images/feira_noturna_real_v2.jpg', NOW() + interval '2 days', '18:00 - 22:00', 'Praça Central'),
(3, 'Concerto no Teatro da Praça', 'Apresentação especial da orquestra municipal com clássicos e música popular brasileira.', 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&q=80&w=1000', NOW() + interval '7 days', '19:30', 'Teatro da Praça');

SELECT setval(pg_get_serial_sequence('public.events', 'id'), (SELECT MAX(id) FROM public.events));

-- Inserir Comércios
insert into public.businesses (id, name, category, image_url, address, phone, website, description, is_featured)
values
(1, 'Panificadora e Confeitaria Araucária', 'Alimentação', '/images/panificadora_araucaria_real.jpg', 'Rua das Flores, 123 - Centro', '(41) 3901-2345', 'padariaexemplo.com.br', 'Pães artesanais, tortas e doces finos. O melhor café da manhã da cidade.', true),
(2, 'Livraria e Sebo Cultural', 'Varejo', 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&q=80&w=1000', 'Av. Victor do Amaral, 456', '(41) 3901-6789', 'livrariaexemplo.com.br', 'Acervo completo de livros novos e usados, vinis e raridades.', false),
(3, 'Auto Mecânica Confiança', 'Serviços', 'https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&q=80&w=1000', 'Rodovia do Xisto, 789', '(41) 3901-1011', 'mecanicaexemplo.com.br', 'Serviços completos de mecânica, elétrica e funilaria para seu veículo.', false),
(4, 'Academia Corpo & Movimento', 'Serviços', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=1000', 'Rua São Vicente, 200 - Centro', '(41) 3642-0000', 'academiacm.com.br', 'Estrutura completa para musculação, crossfit e aulas de dança.', true),
(5, 'Farmácia Saúde Total', 'Varejo', 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?auto=format&fit=crop&q=80&w=1000', 'Av. Archelau de Almeida Torres, 500', '(41) 3643-9999', 'farmaciasaude.com.br', 'Medicamentos, perfumaria e manipulação com os melhores preços.', false),
(6, 'Pet Shop Amigo Fiel', 'Serviços', 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=1000', 'Rua Miguel Bertolino Pizatto, 88', '(41) 3901-5555', 'petshopamigo.com.br', 'Banho, tosa e clínica veterinária 24 horas para seu melhor amigo.', false),
(7, 'Restaurante Sabor da Terra', 'Alimentação', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=1000', 'Rua Pedro Druszcz, 150', '(41) 3642-7777', 'sabordaterra.com.br', 'Buffet por quilo e à la carte com o melhor da comida caseira.', false);

SELECT setval(pg_get_serial_sequence('public.businesses', 'id'), (SELECT MAX(id) FROM public.businesses));
